// Notification templates shared by BDI Corporate and any site generated by the
// BDI website builder. Form types are: contact, newsletter, order, booking.
// Each type ships a customer-facing template (confirmation) and an admin-facing
// template (alert with action items). Brand tokens make them reusable per org.
//
// Keep this file in sync with the copy used by the website-builder generator —
// when generated sites are scaffolded, this module is copied verbatim into them
// (with tenant-specific brand tokens injected at build time).

export interface Brand {
  name: string;
  siteUrl: string;
  supportEmail: string;
  phone?: string;
  primaryColor?: string;
  accentColor?: string;
  logoUrl?: string;
}

const DEFAULT_BRAND: Brand = {
  name: "BDI Corporate",
  siteUrl: "https://bdicorporate.com",
  supportEmail: "info@bdicorporate.com",
  phone: "+961 1 000 000",
  primaryColor: "#0f172a",
  accentColor: "#0ea5e9",
};

function withDefaults(brand?: Partial<Brand>): Brand {
  return { ...DEFAULT_BRAND, ...(brand ?? {}) };
}

function escape(value: unknown): string {
  if (value == null) return "";
  return String(value).replace(/[&<>"']/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c] as string),
  );
}

function shell(brand: Brand, headline: string, subhead: string, body: string): string {
  return `
    <div style="font-family: system-ui, -apple-system, sans-serif; max-width: 600px; margin: 0 auto; background:#fff;">
      <div style="background: linear-gradient(135deg, ${brand.primaryColor}, ${brand.accentColor}); padding: 28px; text-align: center;">
        ${brand.logoUrl ? `<img src="${escape(brand.logoUrl)}" alt="${escape(brand.name)}" style="max-height:40px;margin-bottom:12px;"/>` : ""}
        <h1 style="color: white; margin: 0; font-size: 26px;">${escape(headline)}</h1>
        <p style="color: rgba(255,255,255,0.9); margin: 8px 0 0 0; font-size: 15px;">${escape(subhead)}</p>
      </div>
      <div style="padding: 24px;">${body}</div>
      <div style="text-align:center;padding:16px 24px;color:#94a3b8;font-size:12px;border-top:1px solid #f1f5f9;">
        ${escape(brand.name)} &middot; <a href="${escape(brand.siteUrl)}" style="color:#94a3b8;">${escape(brand.siteUrl.replace(/^https?:\/\//, ""))}</a>
      </div>
    </div>
  `;
}

function row(label: string, value: unknown): string {
  if (value == null || value === "") return "";
  return `
    <tr style="border-bottom: 1px solid #e2e8f0;">
      <td style="padding: 8px 0; color: #64748b; font-size: 14px; width: 160px;">${escape(label)}</td>
      <td style="padding: 8px 0; color: #1e293b; font-weight: 600;">${escape(value)}</td>
    </tr>
  `;
}

// ─── Contact ──────────────────────────────────────────────────────────────

export interface ContactFormPayload {
  name?: string;
  email?: string;
  phone?: string;
  city?: string;
  subject?: string;
  reason?: string;
  budget?: string;
  contact_pref?: string;
  message?: string;
}

export function renderContactCustomerEmail(form: ContactFormPayload, brandIn?: Partial<Brand>): string {
  const brand = withDefaults(brandIn);
  const body = `
    <div style="background:#f0fdf4;padding:16px;border-radius:8px;margin:0 0 16px;border-left:4px solid #059669;">
      <h4 style="margin:0 0 8px;color:#059669;">✓ Your message has been sent</h4>
      <p style="margin:0;color:#059669;font-size:14px;">Thank you for reaching out to ${escape(brand.name)}. Our team will respond within 24 hours.</p>
    </div>
    <h3 style="margin:24px 0 8px;color:#1e293b;">Your submission</h3>
    <div style="background:#f8fafc;padding:16px;border-radius:8px;margin:0 0 16px;">
      <table style="width:100%;border-collapse:collapse;">
        ${row("Name", form.name)}
        ${row("Email", form.email)}
        ${row("Phone", form.phone)}
        ${row("City", form.city)}
        ${row("Subject", form.subject)}
        ${row("Looking for", form.reason)}
        ${row("Budget", form.budget)}
        ${row("Contact preference", form.contact_pref)}
      </table>
      ${form.message ? `<div style="margin-top:16px;padding-top:16px;border-top:1px solid #e2e8f0;">
        <p style="margin:0 0 8px;color:#64748b;font-size:14px;">Your message:</p>
        <p style="margin:0;color:#1e293b;line-height:1.6;white-space:pre-wrap;">${escape(form.message)}</p>
      </div>` : ""}
    </div>
    <div style="background:#eff6ff;padding:16px;border-radius:8px;margin:0 0 16px;">
      <p style="margin:0;color:#0369a1;font-size:14px;">Need immediate help? Reach us at
        <a href="mailto:${escape(brand.supportEmail)}" style="color:#0369a1;">${escape(brand.supportEmail)}</a>${brand.phone ? ` or <a href="tel:${escape(brand.phone)}" style="color:#0369a1;">${escape(brand.phone)}</a>` : ""}.
      </p>
    </div>
  `;
  return shell(brand, "Message received", "We'll get back to you soon", body);
}

export function renderContactAdminEmail(form: ContactFormPayload, brandIn?: Partial<Brand>): string {
  const brand = withDefaults(brandIn);
  const body = `
    <div style="background:#fff7ed;padding:16px;border-radius:8px;margin:0 0 16px;border-left:4px solid #ea580c;">
      <h4 style="margin:0 0 4px;color:#ea580c;">⚡ Action required</h4>
      <p style="margin:0;color:#ea580c;font-size:14px;">Respond within 24 hours${form.contact_pref ? ` via ${escape(form.contact_pref)}` : ""}.</p>
    </div>
    <h3 style="margin:24px 0 8px;color:#1e293b;">Contact details</h3>
    <div style="background:#f8fafc;padding:16px;border-radius:8px;">
      <table style="width:100%;border-collapse:collapse;">
        ${row("Name", form.name)}
        ${form.email ? `<tr style="border-bottom:1px solid #e2e8f0;"><td style="padding:8px 0;color:#64748b;font-size:14px;width:160px;">Email</td><td style="padding:8px 0;"><a href="mailto:${escape(form.email)}" style="color:#0369a1;">${escape(form.email)}</a></td></tr>` : ""}
        ${form.phone ? `<tr style="border-bottom:1px solid #e2e8f0;"><td style="padding:8px 0;color:#64748b;font-size:14px;">Phone</td><td style="padding:8px 0;"><a href="tel:${escape(form.phone)}" style="color:#0369a1;">${escape(form.phone)}</a></td></tr>` : ""}
        ${row("City", form.city)}
        ${row("Subject", form.subject)}
        ${row("Looking for", form.reason)}
        ${row("Budget", form.budget)}
        ${row("Contact preference", form.contact_pref)}
      </table>
    </div>
    ${form.message ? `<div style="background:#eff6ff;padding:16px;border-radius:8px;margin:16px 0;">
      <h3 style="margin:0 0 12px;color:#0369a1;">Message</h3>
      <p style="margin:0;color:#1e293b;line-height:1.6;white-space:pre-wrap;">${escape(form.message)}</p>
    </div>` : ""}
  `;
  return shell(brand, "📩 New contact form", `Submission for ${brand.name}`, body);
}

// ─── Newsletter ──────────────────────────────────────────────────────────

export function renderNewsletterCustomerEmail(email: string, brandIn?: Partial<Brand>): string {
  const brand = withDefaults(brandIn);
  const body = `
    <div style="background:#f0fdf4;padding:16px;border-radius:8px;margin:0 0 16px;border-left:4px solid #059669;">
      <h4 style="margin:0 0 8px;color:#059669;">🎉 You're subscribed</h4>
      <p style="margin:0;color:#059669;font-size:14px;">Welcome aboard, <strong>${escape(email)}</strong>. We'll send updates straight to your inbox.</p>
    </div>
    <h3 style="margin:24px 0 8px;color:#1e293b;">What to expect</h3>
    <ul style="margin:0;padding-left:20px;color:#64748b;line-height:1.8;">
      <li>New product announcements and feature releases</li>
      <li>Subscriber-only deals and early access</li>
      <li>Tips, guides, and industry news</li>
    </ul>
    <div style="background:#eff6ff;padding:20px;border-radius:8px;margin:24px 0;text-align:center;">
      <a href="${escape(brand.siteUrl)}" style="display:inline-block;background:${brand.accentColor};color:white;padding:12px 24px;border-radius:24px;text-decoration:none;font-weight:600;">Explore ${escape(brand.name)}</a>
    </div>
  `;
  return shell(brand, `Welcome to ${brand.name}`, "Thanks for subscribing", body);
}

export function renderNewsletterAdminEmail(email: string, brandIn?: Partial<Brand>): string {
  const brand = withDefaults(brandIn);
  const body = `
    <div style="background:#f8fafc;padding:16px;border-radius:8px;">
      <p style="margin:0;color:#1e293b;">New newsletter subscriber:</p>
      <p style="margin:8px 0 0;font-size:18px;font-weight:600;color:#0369a1;">${escape(email)}</p>
    </div>
  `;
  return shell(brand, "📬 New subscriber", brand.name, body);
}

// ─── Order ──────────────────────────────────────────────────────────────

export interface OrderItem { name?: string; quantity?: number; price?: number; sku?: string; }
export interface OrderPayload {
  number?: string;
  status?: string;
  method?: string;            // stripe | whish | cash | …
  email?: string;
  phone?: string;
  name?: string;
  address1?: string;
  address2?: string;
  city?: string;
  postal?: string;
  country?: string;
  items?: OrderItem[];
  subtotal?: number;
  total?: number;
  currency?: string;
  deliveryFee?: number;
  deliveryMethod?: string;    // pickup | delivery
}

function money(amount: number | undefined, currency: string | undefined): string {
  const n = typeof amount === "number" ? amount : 0;
  const cur = (currency || "USD").toUpperCase();
  try { return new Intl.NumberFormat("en-US", { style: "currency", currency: cur }).format(n); }
  catch { return `${n.toFixed(2)} ${cur}`; }
}

function itemsTable(items: OrderItem[] | undefined, currency: string | undefined): string {
  const rows = (items || []).map((it) => `
    <tr style="border-bottom:1px solid #e2e8f0;">
      <td style="padding:10px 0;color:#1e293b;">${escape(it.name || it.sku || "Item")}</td>
      <td style="padding:10px 0;color:#64748b;text-align:center;">×${escape(it.quantity ?? 1)}</td>
      <td style="padding:10px 0;color:#1e293b;text-align:right;font-weight:600;">${escape(money((it.price ?? 0) * (it.quantity ?? 1), currency))}</td>
    </tr>
  `).join("");
  return `<table style="width:100%;border-collapse:collapse;">${rows}</table>`;
}

export function renderOrderCustomerEmail(order: OrderPayload, brandIn?: Partial<Brand>): string {
  const brand = withDefaults(brandIn);
  const body = `
    <div style="background:#f0fdf4;padding:16px;border-radius:8px;margin:0 0 16px;border-left:4px solid #059669;">
      <h4 style="margin:0 0 8px;color:#059669;">✓ Order ${order.number ? `#${escape(order.number)} ` : ""}received</h4>
      <p style="margin:0;color:#059669;font-size:14px;">${order.method === "stripe" ? "Payment confirmed." : order.method === "whish" ? "We'll confirm your Whish payment shortly." : "We'll be in touch to confirm payment and delivery."}</p>
    </div>
    <h3 style="margin:24px 0 8px;color:#1e293b;">Order summary</h3>
    <div style="background:#f8fafc;padding:16px;border-radius:8px;">
      ${itemsTable(order.items, order.currency)}
      <div style="margin-top:16px;padding-top:16px;border-top:2px solid #e2e8f0;">
        <table style="width:100%;border-collapse:collapse;">
          <tr><td style="padding:4px 0;color:#64748b;">Subtotal</td><td style="padding:4px 0;text-align:right;color:#1e293b;">${escape(money(order.subtotal, order.currency))}</td></tr>
          ${order.deliveryFee ? `<tr><td style="padding:4px 0;color:#64748b;">Delivery</td><td style="padding:4px 0;text-align:right;color:#1e293b;">${escape(money(order.deliveryFee, order.currency))}</td></tr>` : ""}
          <tr><td style="padding:8px 0 0;color:#1e293b;font-weight:700;font-size:16px;">Total</td><td style="padding:8px 0 0;text-align:right;color:#1e293b;font-weight:700;font-size:16px;">${escape(money(order.total, order.currency))}</td></tr>
        </table>
      </div>
    </div>
    ${order.deliveryMethod === "delivery" && order.address1 ? `
      <h3 style="margin:24px 0 8px;color:#1e293b;">Delivery address</h3>
      <div style="background:#f8fafc;padding:16px;border-radius:8px;color:#1e293b;line-height:1.6;">
        ${escape(order.name || "")}<br/>
        ${escape(order.address1)}${order.address2 ? `<br/>${escape(order.address2)}` : ""}<br/>
        ${escape(order.city || "")} ${escape(order.postal || "")}<br/>
        ${escape(order.country || "")}
      </div>
    ` : ""}
  `;
  return shell(brand, "Order confirmed", `Thank you for shopping with ${brand.name}`, body);
}

export function renderOrderAdminEmail(order: OrderPayload, brandIn?: Partial<Brand>): string {
  const brand = withDefaults(brandIn);
  const body = `
    <div style="background:#fff7ed;padding:16px;border-radius:8px;margin:0 0 16px;border-left:4px solid #ea580c;">
      <h4 style="margin:0 0 4px;color:#ea580c;">⚡ New order${order.number ? ` #${escape(order.number)}` : ""}</h4>
      <p style="margin:0;color:#ea580c;font-size:14px;">${escape(order.method || "unknown")} &middot; ${escape(order.deliveryMethod || "—")} &middot; ${escape(money(order.total, order.currency))}</p>
    </div>
    <div style="background:#f8fafc;padding:16px;border-radius:8px;margin-bottom:16px;">
      <table style="width:100%;border-collapse:collapse;">
        ${row("Customer", order.name)}
        ${row("Email", order.email)}
        ${row("Phone", order.phone)}
        ${row("City", order.city)}
        ${row("Method", order.method)}
        ${row("Delivery", order.deliveryMethod)}
      </table>
    </div>
    <h3 style="margin:0 0 8px;color:#1e293b;">Items</h3>
    <div style="background:#f8fafc;padding:16px;border-radius:8px;">${itemsTable(order.items, order.currency)}</div>
  `;
  return shell(brand, "🛒 New order", `Order received for ${brand.name}`, body);
}

// ─── Booking ─────────────────────────────────────────────────────────────

export interface BookingPayload {
  reference?: string;
  serviceName?: string;
  startsAt?: string | Date;
  durationMinutes?: number;
  name?: string;
  email?: string;
  phone?: string;
  notes?: string;
}

function fmtDate(value: string | Date | undefined): string {
  if (!value) return "—";
  const d = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(d.getTime())) return String(value);
  return d.toLocaleString("en-US", { dateStyle: "full", timeStyle: "short" });
}

export function renderBookingCustomerEmail(booking: BookingPayload, brandIn?: Partial<Brand>): string {
  const brand = withDefaults(brandIn);
  const body = `
    <div style="background:#f0fdf4;padding:16px;border-radius:8px;margin:0 0 16px;border-left:4px solid #059669;">
      <h4 style="margin:0 0 8px;color:#059669;">✓ Booking ${booking.reference ? `#${escape(booking.reference)} ` : ""}received</h4>
      <p style="margin:0;color:#059669;font-size:14px;">We'll confirm your appointment shortly.</p>
    </div>
    <div style="background:#f8fafc;padding:16px;border-radius:8px;">
      <table style="width:100%;border-collapse:collapse;">
        ${row("Service", booking.serviceName)}
        ${row("When", fmtDate(booking.startsAt))}
        ${booking.durationMinutes ? row("Duration", `${booking.durationMinutes} min`) : ""}
        ${row("Name", booking.name)}
        ${row("Email", booking.email)}
        ${row("Phone", booking.phone)}
      </table>
      ${booking.notes ? `<div style="margin-top:16px;padding-top:16px;border-top:1px solid #e2e8f0;">
        <p style="margin:0 0 8px;color:#64748b;font-size:14px;">Your notes:</p>
        <p style="margin:0;color:#1e293b;line-height:1.6;white-space:pre-wrap;">${escape(booking.notes)}</p>
      </div>` : ""}
    </div>
  `;
  return shell(brand, "Booking received", `Thanks for booking with ${brand.name}`, body);
}

export function renderBookingAdminEmail(booking: BookingPayload, brandIn?: Partial<Brand>): string {
  const brand = withDefaults(brandIn);
  const body = `
    <div style="background:#fff7ed;padding:16px;border-radius:8px;margin:0 0 16px;border-left:4px solid #ea580c;">
      <h4 style="margin:0 0 4px;color:#ea580c;">⚡ New booking${booking.reference ? ` #${escape(booking.reference)}` : ""}</h4>
      <p style="margin:0;color:#ea580c;font-size:14px;">${escape(booking.serviceName || "Service")} &middot; ${escape(fmtDate(booking.startsAt))}</p>
    </div>
    <div style="background:#f8fafc;padding:16px;border-radius:8px;">
      <table style="width:100%;border-collapse:collapse;">
        ${row("Service", booking.serviceName)}
        ${row("When", fmtDate(booking.startsAt))}
        ${booking.durationMinutes ? row("Duration", `${booking.durationMinutes} min`) : ""}
        ${row("Customer", booking.name)}
        ${row("Email", booking.email)}
        ${row("Phone", booking.phone)}
      </table>
      ${booking.notes ? `<div style="margin-top:16px;padding-top:16px;border-top:1px solid #e2e8f0;">
        <p style="margin:0 0 8px;color:#64748b;font-size:14px;">Customer notes:</p>
        <p style="margin:0;color:#1e293b;line-height:1.6;white-space:pre-wrap;">${escape(booking.notes)}</p>
      </div>` : ""}
    </div>
  `;
  return shell(brand, "📅 New booking", `For ${brand.name}`, body);
}

// ─── Brand presets ───────────────────────────────────────────────────────

export const BDI_BRAND: Brand = {
  name: "BDI Corporate",
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL || "https://bdicorporate.com",
  supportEmail: process.env.ADMIN_EMAIL || "info@bdicorporate.com",
  phone: "+961 1 000 000",
  primaryColor: "#0019FF",
  accentColor: "#00C774",
};
